### PR TITLE
Update CSS of player client

### PR DESCRIPTION
**Pull request by leungleoqin**
- Also refactored text-only components.
- Also refactored Timer component to take a 'seconds' props.

### CODE REVIEW

**Comment by Lynne-Daniels** [comment]
The player looks beautiful. Nice work!  One small change needed --  index_presenter.html needs the stylesheet href updated.   Also,  I just noticed the timer file in the presenter directory is an old version that continues changing the time for 20 seconds even if unmounted.  Would it make sense to copy over the code in the player timer to the presenter timer in this branch?

**Review by lamdbui — APPROVED** [review]
Agreed with @Lynne-Daniels. It looks great! 
For the timer issue, if we want to update that, we can fix that in a separate PR as well.

@Lynne-Daniels , if you are okay with that, I'll let you do the merge.

**Comment by Lynne-Daniels** [comment]
I'm ok with fixing the timer issue later.  The css href breaks the application and has to be fixed.  Can I fix it from here, or does the pull request need to be updated?

**Comment by lamdbui** [comment]
@Lynne-Daniels , you can fix it and just push the changes to the same branch. The changes would be reflected here.

**Review by Lynne-Daniels — APPROVED** [review]
Looks nice!  I fixed the css href as described in comments.  Will merge now.

**Pull request merged**
