### PR TITLE
Refactor client to be split into presenter and player options

### PR DESCRIPTION
**Pull request by lamdbui**
index_presenter.html
index_player.html

### CODE REVIEW

**Comment by Lynne-Daniels** [comment]
this branch deleted some of the css styles.  I saved a copy and will send another pull request.

**Comment by lamdbui** [comment]
Doh - sorry about that @Lynne-Daniels . There were a lot of random little changes. I must've missed the css stuff

**Comment by Lynne-Daniels** [comment]
No it was really weird.  It was missing on the branch, but came back on the merge.  But....webpack isn't handling changes properly.  I'm trying out some packages to see if I can get a nice solution.

**Comment by lamdbui** [comment]
Strange. What problems are you having on webpack? The latest stuff in
develop is able to compile okay on my side. The two new files are
index_player.html and index_presenter.html and seem to be opening fine on
Chrome.

**Pull request merged**
